In [ ]:
import pandas as pd

In [ ]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (1.5.3)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2022.7.1)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.22.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)

In [ ]:
df=pd.read_csv("services.csv")

In [ ]:
df.head()

,id,location_id,program_id,accepted_payments,alternate_name,application_process,audience,description,eligibility,email,...,interpretation_services,keywords,languages,name,required_documents,service_areas,status,wait_time,website,taxonomy_ids
0,1,1,NaN,NaN,NaN,Walk in or apply by phone.,"Older adults age 55 or over, ethnic minorities...",A walk-in center for older adults that provide...,"Age 55 or over for most programs, age 60 or ov...",NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Fair Oaks Adult Activity Center,NaN,Colma,active,No wait.,NaN,NaN
1,2,2,NaN,NaN,NaN,Apply by phone for an appointment.,Residents of San Mateo County age 55 or over,Provides training and job placement to eligibl...,"Age 55 or over, county resident and willing an...",NaN,...,NaN,"EMPLOYMENT/TRAINING SERVICES, Job Development,...",NaN,Second Career Employment Program,NaN,San Mateo County,active,Varies.,NaN,NaN
2,3,3,NaN,NaN,NaN,Phone for information (403-4300 Ext. 4322).,Older adults age 55 or over who can benefit fr...,Offers supportive counseling services to San M...,Resident of San Mateo County age 55 or over,NaN,...,NaN,"Geriatric Counseling, Older Adults, Gay, Lesbi...",NaN,Senior Peer Counseling,NaN,San Mateo County,active,Varies.,NaN,NaN
3,4,4,NaN,NaN,NaN,Apply by phone.,"Parents, children, families with problems of c...",Provides supervised visitation services and a ...,None,NaN,...,NaN,"INDIVIDUAL AND FAMILY DEVELOPMENT SERVICES, Gr...",NaN,Family Visitation Center,NaN,San Mateo County,active,No wait.,NaN,NaN
4,5,5,NaN,NaN,NaN,Phone for information.,Low-income working families with children tran...,Provides fixed 8% short term loans to eligible...,Eligibility: Low-income family with legal cust...,NaN,...,NaN,"COMMUNITY SERVICES, Speakers, Automobile Loans",NaN,Economic Self-Sufficiency Program,NaN,San Mateo County,active,NaN,NaN,NaN

In [ ]:
df.tail()

,id,location_id,program_id,accepted_payments,alternate_name,application_process,audience,description,eligibility,email,...,interpretation_services,keywords,languages,name,required_documents,service_areas,status,wait_time,website,taxonomy_ids
18,19,19,NaN,NaN,NaN,Call for screening appointment (650-347-3648).,NaN,Provides free medical and dental care to those...,Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,San Mateo Free Medical Clinic,NaN,"Belmont, Burlingame",active,Varies.,NaN,NaN
19,20,20,NaN,NaN,NaN,Walk in.,NaN,no unrequired fields for this service,NaN,NaN,...,NaN,NaN,NaN,Service with blank fields,NaN,NaN,defunct,NaN,NaN,NaN
20,21,21,NaN,NaN,NaN,By phone during business hours.,NaN,just a test service,NaN,NaN,...,NaN,NaN,NaN,Service for Admin Test Location,NaN,San Mateo County,inactive,NaN,NaN,NaN
21,22,22,NaN,"Cash, Check, Credit Card",Fotos para pasaportes,Walk in or apply by phone or mail,"Profit and nonprofit businesses, the public, m...",[NOTE THIS IS NOT A REAL SERVICE--THIS IS FOR ...,None,passports@example.org,...,We offer 3-way interpretation services over th...,"Salud, Medicina",Spanish,Passport Photos,Government-issued picture identification,"Alameda County, San Mateo County",active,No wait to 2 weeks.,http://www.example.com,"105, 108, 108-05, 108-05-01, 111, 111-05"
22,23,22,NaN,NaN,NaN,Walk in or apply by phone or mail,"Second service and nonprofit businesses, the p...",[NOTE THIS IS NOT A REAL ORGANIZATION--THIS IS...,None,NaN,...,NaN,"Ruby on Rails/Postgres/Redis, testing, wic",NaN,Example Service Name,NaN,"San Mateo County, Alameda County",active,No wait to 2 weeks,http://www.example.com,NaN

In [ ]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
df.columns

Index(['id', 'location_id', 'program_id', 'accepted_payments',
       'alternate_name', 'application_process', 'audience', 'description',
       'eligibility', 'email', 'fees', 'funding_sources',
       'interpretation_services', 'keywords', 'languages', 'name',
       'required_documents', 'service_areas', 'status', 'wait_time', 'website',
       'taxonomy_ids'],
      dtype='object')

In [ ]:
#to see as list
list(df.columns)

['id',
 'location_id',
 'program_id',
 'accepted_payments',
 'alternate_name',
 'application_process',
 'audience',
 'description',
 'eligibility',
 'email',
 'fees',
 'funding_sources',
 'interpretation_services',
 'keywords',
 'languages',
 'name',
 'required_documents',
 'service_areas',
 'status',
 'wait_time',
 'website',
 'taxonomy_ids']

In [ ]:
df['service_areas']

0                                     Colma
1                          San Mateo County
2                          San Mateo County
3                          San Mateo County
4                          San Mateo County
5                          San Mateo County
6       Belmont, Burlingame, East Palo Alto
7                   Belmont, East Palo Alto
8                          San Mateo County
9                          San Mateo County
10                         San Mateo County
11                                Daly City
12                         San Mateo County
13      Belmont, Burlingame, East Palo Alto
14         Alameda County, San Mateo County
15                                      NaN
16    Colma, Daly City, South San Francisco
17                           East Palo Alto
18                      Belmont, Burlingame
19                                      NaN
20                         San Mateo County
21         Alameda County, San Mateo County
22         San Mateo County, Alameda County
Name: service_areas, dtype: object

In [ ]:
type(df['service_areas'])

pandas.core.series.Series

In [ ]:
list(df['service_areas'])

['Colma',
 'San Mateo County',
 'San Mateo County',
 'San Mateo County',
 'San Mateo County',
 'San Mateo County',
 'Belmont, Burlingame, East Palo Alto',
 'Belmont, East Palo Alto',
 'San Mateo County',
 'San Mateo County',
 'San Mateo County',
 'Daly City',
 'San Mateo County',
 'Belmont, Burlingame, East Palo Alto',
 'Alameda County, San Mateo County',
 nan,
 'Colma, Daly City, South San Francisco',
 'East Palo Alto',
 'Belmont, Burlingame',
 nan,
 'San Mateo County',
 'Alameda County, San Mateo County',
 'San Mateo County, Alameda County']

In [ ]:
list(df['status'])

['active',
 'active',
 'active',
 'active',
 'active',
 'active',
 'active',
 'active',
 'active',
 'active',
 'active',
 'active',
 'active',
 'active',
 'active',
 'active',
 'active',
 'active',
 'active',
 'defunct',
 'inactive',
 'active',
 'active']

In [ ]:
df[['status']]

      status
0     active
1     active
2     active
3     active
4     active
5     active
6     active
7     active
8     active
9     active
10    active
11    active
12    active
13    active
14    active
15    active
16    active
17    active
18    active
19   defunct
20  inactive
21    active
22    active

In [ ]:
df.columns

Index(['id', 'location_id', 'program_id', 'accepted_payments',
       'alternate_name', 'application_process', 'audience', 'description',
       'eligibility', 'email', 'fees', 'funding_sources',
       'interpretation_services', 'keywords', 'languages', 'name',
       'required_documents', 'service_areas', 'status', 'wait_time', 'website',
       'taxonomy_ids'],
      dtype='object')

In [ ]:
#selecting multiples pass as list
df[['email','keywords']]

                    email                                           keywords
0                     NaN  ADULT PROTECTION AND CARE SERVICES, Meal Sites...
1                     NaN  EMPLOYMENT/TRAINING SERVICES, Job Development,...
2                     NaN  Geriatric Counseling, Older Adults, Gay, Lesbi...
3                     NaN  INDIVIDUAL AND FAMILY DEVELOPMENT SERVICES, Gr...
4                     NaN     COMMUNITY SERVICES, Speakers, Automobile Loans
5                     NaN  ADULT PROTECTION AND CARE SERVICES, In-Home Su...
6                     NaN  ADULT PROTECTION AND CARE SERVICES, Adult Day ...
7                     NaN  ADULT PROTECTION AND CARE SERVICES, Meal Sites...
8                     NaN  EDUCATION SERVICES, Library, Libraries, Public...
9                     NaN  EDUCATION SERVICES, Library, Libraries, Public...
10                    NaN  EDUCATION SERVICES, Library, Libraries, Public...
11                    NaN  EDUCATION SERVICES, Adult, Alternative, Litera...
12                    NaN  EDUCATION SERVICES, Library, Libraries, Public...
13                    NaN  COMMUNITY SERVICES, Interpretation/Translation...
14                    NaN  ALCOHOLISM SERVICES, Residential Care, DRUG AB...
15                    NaN  COMMODITY SERVICES, Clothing/Personal Items, C...
16                    NaN  COMMODITY SERVICES, Clothing/Personal Items, C...
17                    NaN  HEALTH SERVICES, Outpatient Care, Community Cl...
18                    NaN  HEALTH SERVICES, Outpatient Care, Community Cl...
19                    NaN                                                NaN
20                    NaN                                                NaN
21  passports@example.org                                    Salud, Medicina
22                    NaN         Ruby on Rails/Postgres/Redis, testing, wic

In [ ]:
df.dtypes

id                           int64
location_id                  int64
program_id                 float64
accepted_payments           object
alternate_name              object
application_process         object
audience                    object
description                 object
eligibility                 object
email                       object
fees                        object
funding_sources             object
interpretation_services     object
keywords                    object
languages                   object
name                        object
required_documents          object
service_areas               object
status                      object
wait_time                   object
website                     object
taxonomy_ids                object
dtype: object

In [ ]:
#suppose i have excel sheet and now i have to read data from excel sheet

df1 = pd.read_excel("LUSID Excel - Setting up your market data.xlsx")

In [ ]:
type(df1)

pandas.core.frame.DataFrame

In [ ]:
df1.dtypes

Unnamed: 0    float64
Unnamed: 1    float64
Unnamed: 2    float64
Unnamed: 3     object
Unnamed: 4     object
Unnamed: 5     object
Unnamed: 6    float64
Unnamed: 7     object
Unnamed: 8     object
Unnamed: 9     object
dtype: object

In [ ]:
df1.columns

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9'],
      dtype='object')

In [ ]:
df1[['Unnamed: 0','Unnamed: 1']]

    Unnamed: 0  Unnamed: 1
0          NaN         NaN
1          NaN         NaN
2          NaN         NaN
3          NaN         NaN
4          NaN         NaN
5          NaN         NaN
6          NaN         NaN
7          NaN         NaN
8          NaN         NaN
9          NaN         NaN
10         NaN         NaN
11         NaN         NaN
12         NaN         NaN
13         NaN         NaN
14         NaN         NaN
15         NaN         NaN
16         NaN         NaN
17         NaN         NaN
18         NaN         NaN
19         NaN         NaN
20         NaN         NaN
21         NaN         NaN
22         NaN         NaN
23         NaN         NaN
24         NaN         NaN
25         NaN         NaN
26         NaN         NaN
27         NaN         NaN